### ISSUE TITLE
VNC View is linked to Localhost

### ISSUE THREAD

**Issue by tnobody** [ConSol/sakuli-ui#68]

**Comment by toschneck** [comment]
linked to #60 
Maybe a revers proxy can help? https://github.com/ConSol/docker-headless-vnc-container/issues/67#issuecomment-370646129

**Comment by tnobody** [comment]
Not sure if we can configure nginx to expose endpoints for the dedicated running testinstances. Right now they are distiguishable from the dynamic assigned port on the docker host. A proxy must dynamically transform the port to the url.
E.g.
<dockerhost>:<vnc-web-port>
Should be proxied by something like:
<sakuli-ui-host>:<sakuli-ui-port>/<test-instance-id>

**Comment by toschneck** [comment]
works well on local and remote system! Great solution @tnobody !
