### ISSUE TITLE
Reduce git repo size

### ISSUE THREAD

**Issue by joroboro** [ConSol/sakuli-ui#71]
search for node modules within the git repo and remove them to reduce the whole size of the sakuli-ui git repo.

**Comment by toschneck** [comment]
After **NO** local changes are at the repos we can go the following way from https://rtyley.github.io/bfg-repo-cleaner/:
```bash
mkdir tmp && cd tmp
git clone --mirror git@github.com:ConSol/sakuli-ui.git
java -jar ~/Downloads/bfg-1.13.0.jar --delete-folders repository sakuli-ui.git
cd sakuli-ui-git
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push
```
After this, every local copy have to be **deleted locally** and **replaced by a fresh `git clone` copy** to avoid 
some issues!
