### ISSUE TITLE
`.` as root path

### ISSUE THREAD

**Issue by toschneck** [ConSol/sakuli-ui#79]
If i execute the following command, the workspace to select is empty

    java -Dsakuli.home.folder=/home/tschneck/sakuli/sakuli-v1.2.0-SNAPSHOT -Dsakuli.ui.root.directory=. -jar /home/tschneck/sakuli/sakuli-v1.2.0-SNAPSHOT/libs/ui/java/sakuli-ui-web.jar

Maybe the root Path has to be resolved before it will be used :thinking: 
![image](https://user-images.githubusercontent.com/4659261/39351435-ca3e329e-4a01-11e8-96e4-82262b8b6b5f.png)

**Comment by tnobody** [comment]
What is your expectation? If you want to set the current folder (from where the server is started) please try $PWD

**Comment by toschneck** [comment]
I think if you do a `Paths.get(".").normalize().toAbsolutePath()` on the startup where you set the root Path it would solve the issue.
